### PR TITLE
Fix rx buffer allocation

### PR DESCRIPTION
**Pull request by zuckschwerdt**
- Fix activateStream loosing the first buffer
- Fix set_buffer_size failing to alloc the default size buffer
- Fix log format about selected buffer size

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
@vsonnier please test and rebase your changes, this will go in asap as hotfix.

**Comment by vsonnier** [comment]
@zuckschwerdt Go on, push that on master I'll manage #14 rebase on top of it afterwards.

**Comment by vsonnier** [comment]
Nevermind, I've manually merged the (very small) difference in #14.

**Comment by zuckschwerdt** [comment]
Ok, I'll let this sit for a day so other people can get a word in if needed.

**Pull request merged**
