### PR TITLE
Add uninstall target

### PR DESCRIPTION
**Pull request by willcode**
Signed-off-by: Jeff Long <willcode4@gmail.com>

### CODE REVIEW

**Comment by zuckschwerdt** [comment]
Where does `install_manifest.txt` come from? And shouldn't that only ever contain `libPlutoSDRSupport.so` / `librtlsdrSupport.so` (pothosware/SoapyRTLSDR#55)?

**Comment by willcode** [comment]
cmake places `install_manifest.txt` in the build directory. The `uninstall` target is only useful when the build directory is still around. (Just saw your updated comment ...)

This is a generic way of doing uninstall. Possibly overkill for a single shared object, but it's copied from SoapySDR. The purpose of adding this target is so that PyBOMBS will work better for the `remove` and `update` targets.

**Comment by zuckschwerdt** [comment]
for quick reference, it's mostly verbatim the [AddUninstallTarget](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/recipe/AddUninstallTarget) recipe from the cmake wiki.

**Comment by guruofquality** [comment]
kind of wished cmake just included this as a standard macro, this is an old issue with cmake and I guess Makefile generation

**Pull request merged**
